### PR TITLE
Update location of GSI repository in Externals.cfg.

### PR DESCRIPTION
**Pull request by christopherwharrop-noaa**
Update tags in Externals.cfg to be consistent with sorc/checkout.sh

### CODE REVIEW

**Comment by christopherwharrop-noaa** [comment]
@danielabdi-noaa / @markgovett - I have specified both of you as reviewers for this PR. You should have gotten an email from GitHub notifying you of that. I am writing this comment in the PR interface using the @ symbol to directly address you for correspondence regarding this PR. You should also get an email notifying you of this comment. You can respond in Github (recommended) or via email (not recommended). I need you to review this PR and either approve it, or request changes, or reject it. I can merge after 1 approval.

**Review by danielabdi-noaa — APPROVED** [review]
Testing approval

**Comment by christopherwharrop-noaa** [comment]
@danielabdi-noaa - Thank you for your approval. I can now merge. Note that "Squash and Merge" is the preferred merge method. Also note that a "Remove Branch" button will appear after you click the green "Merge pull request" button to remove the branch you just merged. ALWAYS remove the branch you just merged to keep the repository clean. Please go ahead and try merging this.

**Comment by christopherwharrop-noaa** [comment]
@danielabdi-noaa - Also make sure you actually look at the PR and give it a thorough review to make sure it looks ok. Also, since we don't have continuous integration set up, you should normally check out the branch the PR wants to merge and test it to make sure it works before approving. Never just blindly approve a PR; look at the changes and be critical of them.

**Comment by danielabdi-noaa** [comment]
Chris, I am not authorized to merge pull request, the button is disable for me.

**Comment by christopherwharrop-noaa** [comment]
@danielabdi-noaa - Try refreshing the page and see if it's available now.

**Comment by christopherwharrop-noaa** [comment]
@danielabdi-noaa - BTW, if you want to address me directly in a comment, you can type "@" and it will bring up a list of users and you can select mine, and I'll get notified directly.

**Pull request merged**
